export const appInitialValue = {
  // id_empresa: 0,
  // aplicacao: null,
  chave_1: 0,
  chave_2: '---',
  chave_3: '---',
  chave_4: '---',
  chave_5: '---',
  chave_6: '---',
  chave_7: '---',
  chave_8: new Date(),
  cod_categoria: '',
  desc_aplicacao: '',
  valor_date_1: new Date(),
  valor_date_2: new Date(),
  valor_date_3: new Date(),
  valor_number_1: 0,
  valor_number_2: 0,
  valor_number_3: 0,
  valor_number_4: 0,
  valor_number_5: 0,
  valor_string_1: '---',
  valor_string_2: '---',
  valor_string_3: '---',
  valor_string_4: '---',
  valor_string_5: '---',
  valor_string_6: '---',
  valor_string_7: '---',
  valor_string_8: '---',
  valor_string_9: '---',
  valor_string_10: '---',
  // user_insert: null,
  // user_update: null,
};
